* Encyclopaedia Brittanica

   De http://www.britannica.com/EBchecked/topic/629151/Villard-De-Honnecourt
    
   Villard De Honnecourt, (born c. 1225, Picardy, Fr.—died c. 1250),
   French architect remembered primarily for the sketchbook compiled
   while he travelled in search of work as a master mason. The book is
   made up of sketches and writings concerning architectural practices
   current during the 13th century.
    
   Honnecourt spent most of his life travelling to such places as Rheims,
   Chartres, Laon, Meaux, and Lausanne. He visited Hungary in 1245,
   possibly to work there as an architect. His sketches indicate that he
   was well acquainted with the great churches that were built during his
   lifetime. Little mention is made of Honnecourt’s own architectural
   contributions, although he may have been active in the building of
   Saint-Quentin. In his notes Honnecourt described the work he did on
   the rose window of Lausanne cathedral.
    
   The architect’s sketchbook was originally devoted entirely to sketches
   marked by sinuous figures in draped robes. Eventually, Honnecourt
   compiled a manual that gave precise instructions for executing
   specific objects with explanatory drawings. In his writings he fused
   principles passed on from ancient geometry, medieval studio
   techniques, and contemporary practices. The author includes sections
   on technical procedures, mechanical devices, suggestions for making
   human and animal figures, and notes on the buildings and monuments he
   had seen. He also offers insights into the variety of interests and
   work of the 13th-century master mason in addition to providing an
   explanation for the spread of Gothic architecture in Europe.

* Wikipedia

  Villard de Honnecourt (Wilars dehonecort, fol. 1v; Vilars de
  Honecourt, fol. 15v) was a 13th-century artist from Picardy in
  northern France. He is known to history only through a surviving
  portfolio of 33 sheets of parchment containing about 250 drawings
  dating from the 1220s/1240s, now in the Bibliothèque Nationale,
  Paris (MS Fr 19093). The great variety of subjects (religious and
  secular figures suitable for sculpture, and architectural plans,
  elevations and details, ecclesiastical objects and mechanical
  devices, some with annotations), makes it difficult to determine its
  purpose. Other subjects such as animals and human figures also
  appear.
   
  The traditional view, since the discovery of the portfolio in the
  mid-19th century, is that Villard was an itinerant
  architect/mason/builder, but there is no evidence of him ever
  working as an architect or in any other identifiable
  profession. Nonetheless, it is clear from his drawings that he was
  interested in architecture and that he traveled to some of the major
  ecclesiastical building sites of his day to record details of these
  buildings. His drawing of one of the west facade towers of Laon
  Cathedral and those of radiating chapels and a main vessel bay,
  interior and exterior, of Rheims Cathedral are of particular
  interest.
   
  Villard tells us, with pride, that he had been in many lands (Jai
  este en m[u]lt de tieres) and that he made a trip to Hungary where
  he remained many days (maint ior), but he does not say why he went
  there or who sent him. It has recently been proposed that he may
  have been a lay agent or representative of the cathedral chapter of
  Cambrai Cathedral to obtain a relic of St. Elizabeth of Hungary who
  had made a donation to the cathedral chapter and to whom the chapter
  dedicated one of the radiating chapels in their new chevet.
   
  Among the mechanical devices Villard sketched are a perpetual-motion
  machine, a water-driven saw, a number of automata, lifting devices,
  war engines (a trebuchet) as well as a number of anatomical and
  geometric sketches for portraiture and architecture. The claim that
  he drew a simple escapement mechanism, the first known in the West,
  is now questioned.
   
  Villard's vast diversity in his sketchbook has caused him to be
  compared to Leonardo da Vinci, who also specialized in many
  different categories of art and science.

* Columbia coiso, provavelmente Teresa G. Frish

    ** Teresa G. Frisch, Gothic Art 1140 - c. 1450: Sources and
   Documents, University of Toronto Press in association with the
   Medieval Academy of America, 1987.
	
  Until the end of the thirteenth century, and frequently during the
  following century as well, the architect was known as "mason", and no
  distinction seems to have been made with regard to specialization and
  rank. (1) We may assume that his professional training was that of any
  mason, which began with his apprenticeship as a stone cutter, and that
  he gradually acquired prominence because of his special gifts and his
  general intelligence. These led him to special tasks, which in turn
  probably led him to commanding technical, artistic and administrative
  assignments, to higher pay, and to certain exclusive social
  privileges. The first steps toward such a career may have been easier
  for the young mason who was born into a family of distinguished
  architects, for there is evidence that successive generations of
  certain families retained leading positions in the employment of the
  same patron.
   
  The only known personal record of an architect's interests and
  concerns in the thirteenth century is the lodge book of Villard de
  Honnecourt .(2) What is known of Villard's life and career has been
  extracted from this lodge book. His name and dialect indicate that he
  was born in Honnecourt, a small town near Cambrai in northeastern
  Picardy at the frontiers of Artois and Flanders. We do not know the
  dates of his birth or death, but his style of drawing the human
  figure, his choice of architectural details and his observations imply
  that he was at the height of his career in the first part of the
  thirteenth century. We may assume that he received his early training
  near home, and perhaps at the large Cistercian abbey of Vaucelles,
  which was built between 1190 and 1216 and dedicated in 1235. (3) It is
  interesting to note that there is a ground plan of the choir of this
  church among his drawings.
   
  Together with another architect, Pierre de Corbie, Villard designed a
  characteristically Cistercian end of a choir with double ambulatory
  and chapels. He drew the ground plan of the presbytery of the
  Cistercian church of Saint Stephen at Meaux, a church begun in 1163,
  far along by 1198 and rebuilt in 1253. He also drew an ideal ground
  plan of a Cistercian church with a rectangular choir. We may therefore
  assume that Villard worked for the Cistercians. He was also familiar
  with the plans of the cathedral of Cambrai and may have worked there,
  for he drew the ground plan of the choir and the elevation before the
  church was much beyond the planning stage. The cathedral was begun in
  1227 and work on it proceeded until sometime between 1230 and 1231,
  when all building activity was interrupted. It must have been shortly
  after 1231 when Villard wrote of his concern for the future of this
  construction while sketching architectural details during building
  operations at the cathedral at Reims where, according to his drawings,
  the choir and the first bays of the nave were under construction. (4)
   
  From Reims Villard went to Hungary, a journey he mentions on several
  occasions. It may be that his association with the Cistercians led to
  a contract there. The only artistic reminiscence of this trip is a
  sketch of the floor mosaic of a church.
   
  Perhaps while on his way east, Villard added to his sketches the west
  towers of the cathedral at Laon of about 1210; the rose window of the
  west facade at Chartres of before 1215: (5) and the rose window of the
  south transept of the cathedral at Lausanne, also of the first quarter
  of the thirteenth century. (6)
   
  It is generally assumed that Villard returned from Hungary before the
  Tartar invasion of 1241 and that he spent the rest of his active life
  in Picardy, perhaps as master of the lodge at the collegiate church at
  Saint Quentin, where one of the largest Cistercian abbey churches of
  France was then being built. (7)
   
  Villard's lodge book was compiled informally over a period of years as
  he observed, sketched and recorded solutions to architectural and
  technological tasks, human and animal forms and selected other
  objects. Eventually he put the drawings into a portfolio and supplied
  some of them with comments. Later he added technical drawings dealing
  with building methods, measurement and applied geometry for the
  everyday needs of a stonemason's lodge.
   
  Beyond the evidence of a competent hand in drawing, the book reveals a
  discerning eye and mind, astute in absorbing and evaluating a great
  variety of ideas; it shows a man conversant with the scientific,
  theoretical and artistic trends of his age. To judge from the variety
  of subjects his observations encompass, his tasks must have been as
  numerous, diverse and demanding as those of which the Roman architect
  Vitruvius speaks. (8)
   
  Villard's associates at a lodge over which he presided later in his
  life made some additions of a practical nature to the book. Master II,
  who appears to have been most closely connected with Villard, added
  various comments and a set of detailed technical drawings relating to
  the stonemason's daily tasks in applied geometry and
  measurement. Master III contributed only some textual additions,
  frequently supplementing earlier entries by Villard. Neither man added
  to Villard's aesthetic observations or to his collection of
  engineering constructions and inventions.
   
  Villard's drawings are characteristic of the artistic trends of the
  first quarter of the thirteenth century. His advice is sober and
  direct, now and then interspersed with phrases which he must have seen
  in existing technical literature. (9) Yet he never fails to convey his
  own opinion concerning the relative worth of an artistic or technical
  solution to a problem and he invariably points to the ingenious and to
  the uniquely satisfactory.
   
  When his sketchbook became a lodge book, Villard added an opening
  address to the reader:
   
  Villard de Honnecourt gives you greeting and beseeches all who will
  work by the aids that are found in this book to pray for his soul and
  bear him in remembrance. For in this book one can obtain good advice
  on the grand craft of maconerie and the engiens de carpenterie, and
  you will find in it the art of drawing . . . the principal features
  (les trais), as the discipline of geometry . . . requires and teaches
  them. (10)
   
  Villard's drawings fall into six main categories: (1) animals; (2)
  human figures; (3) interior furnishings and ornaments; (4)
  architectural drawings; (5) carpentry and wooden constructions; (6)
  masonry and geometry.
   
  In view of the love for animal representations in medieval sculpture
  and painting for allegorical, symbolic and decorative purposes,
  Villard's collection is modest; animals are rendered in conventional
  poses as selected from illuminated bestiaries and sample books. A
  generation later there was to be closer observation of nature,
  especially in informal scenes. The drawings of a lion and of a lion
  training scene are the only ones Villard claims were drawn from
  life. This is the more remarkable because it is quite apparent that
  here too he used artistic conventions taken from a model book of
  Byzantine, late classic or oriental derivation. (11) He says:
   
  The lion. I will tell you of the training of the lion. He who trains
  the lion has two dogs. When he wants the lion to do something and the
  lion growls, he beats his dogs. When the lion sees the dogs being
  beaten he becomes afraid and does as he is told. I will not speak of
  the lion when he is in a rage, for then he would not do what anybody
  tells him, either good or bad. And you should know that this lion was
  drawn from life.
   
  Hahnloser counts 163 drawings of the human figure. (12) They are an
  odd assortment of individuals and groups in biblical, allegorical and
  narrative scenes. Several times Villard copied the nude male figure
  from late classic or Byzantine models, indicating an interest in
  ancient art far greater than the obvious usefulness to him of these
  figures in the rendition of the nude in biblical representations.
   
  Advanced for this moment in French art is the suffering expressed in
  the drawings of two crucifixions, showing Christ with crossed feet
  pierced by a single nail; equally expressive is a Descent from the
  Cross, while the bust drawing of the Virgin and Child follows the
  style and restrained mood of the sculpture of the cathedral of Reims
  of about 1230. All Villard's examples are of elegant and noble
  proportions and are eloquent in their gestures. As has often been
  observed, they reflect in their proportions, poses and drapery
  treatment the figure style of the transept facades at Chartres and
  that of the north transept and the earliest west facade statues at
  Reims cathedral of 1224-1230.
   
  The lodge book also contains drawings describing a great variety of
  aesthetically pleasing or technically ingenious interior furnishings
  and ornaments. For example, Villard says of Plate 11: "Of this manner
  was the tomb of a heathen which 1 once saw." He shows a full-page
  architectural setting of a throne with a youthful ruler dressed in a
  toga, with a pair of standing genii (ignudi) holding a victory wreath
  above him and an altar with two acclaiming toga-draped male figures on
  either side of the altar below. One wonders whether Villard may have
  seen a stone relief of late Roman origin, showing the apotheosis of an
  emperor. Despite errors of perspective, the drawing conveys clearly
  the original object's compositional merits.
   
  Of Plate 12 he says:
   
  He who wishes to make a clock-case can see here one that I once
  saw. From below, the first story is square and has four gables. The
  story above is eight-sided and roofed, and above that four small
  gables, the space between two and two of them being empty. The
  uppermost story is square with four small gables, and the turret above
  is eight-sided.
   
  And of Plate 13:
   
  He who wishes to make a lectern from which to read the Gospel, behold
  the best manner of making it. First there are three serpents which
  rest on the ground and over them a three-lobed slab, and above that
  three serpents of a different kind and columns of the same height as
  the serpents, and over that a triangular slab. After this, you can see
  for yourself in what manner the lectern is made. Here is its image. In
  the midst of the three columns there must be a rod to carry the knob
  on which the eagle sits. (63)
   
  To this group also belong three drawings of arm rests and the wing of
  a choir stall with a remarkably beautiful acanthus design. With this
  goes Villard's comment: "If you wish to make a satisfactory wing of a
  truly good choir stall, see this one." Similarly crisp and luxuriant
  foliage occurs in several other plates. (14)
   
  Other objects in this group include a handwarmer, as we are told by
  Villard, for use by the officiating bishop during the cold, damp
  winter months. The receptacle, which looks like a brass apple, holds
  the charcoal in such a way that no matter how it is turned in the
  pocket the hot coals will not spill out. On the same page. (15)
  Villard shows one of several "wonders" (mirabilia) he drew: a wine or
  water container working like a siphon which, when activated, causes a
  small hollow bird perched on a tiny tower in the middle of the bowl to
  drink the liquid.
   
  Judging from the number and careful execution of these drawings and
  the relatively detailed comments, Villard's main interest seems to
  have centered on demonstrating in the lodge book the excellence of
  architectural design and its structural and aesthetic effectiveness,
  down to the smallest detail. On this subject, he comments:
   
  I have been in many countries, as you can judge from this book, but
  nowhere have I seen a tower such as the one at Laon. Notice the ground
  plan of the first story there where it springs at the level of the
  first windows. At this level the tower is surrounded by eight
  buttresses. Four square turrets rest on clusters of three colonnettes
  each. This is followed upward by open arches and a horizontal molding
  and more turrets with eight columns, and from between two of these an
  ox peers out. This in turn is followed by an arcade and a horizontal
  molding, and an eightsided helmet, each side having a slit for
  light. Consider this carefully, for you will learn from it about how
  to construct and raise such a structure and how the turrets alternate
  in shape. And pay good heed to your work, for if you wish to make a
  good tower you must choose buttresses of sufficient depth. Do apply
  all your attention to your work, for only then can you do that which
  is worthy of a wise and noble man. (16)
   
  Behold one of the windows at Reims from the bays of the nave such as
  they are between two piers. I was commissioned to go to the land of
  Hungary when I drew it because I liked it best. (17)
   
  Behold the ground plan of the choir of the church of Our Lady of
  Cambrai as it rises from the ground. Earlier in this book you will
  find the interior and exterior elevations and the manner in which the
  chapels, the plain walls and also the buttresses will look. (18)
   
  Observe here the rising structure of the chapels of the church at
  Reims and how they are in the interior elevation; the interior
  passages and the hidden vaulted-in passages; and on this other page
  you can see the rising structure of the chapels of the church at Reims
  from the exterior from floor to top, just as they are. Of such a kind
  will those at Cambrai have to be if one will do them justice. The
  topmost story must have a battlement. (19)
   
  Behold the drawings of the elevation of the church of Reims [and] of
  the wall inside and outside. The first story of the aisles must form a
  battlemented parapet so that a passage can lead around in front of the
  roof.
   
  Against this roof on the inside are [built] passageways, and, where
  these passages are vaulted in and paved, there the passages lead
  outside, so that one can walk past along the sills of the windows.
   
  And the topmost story must have battlements so that one can go around
  the roof.
   
  Behold the manner and method of the whole elevation. (20)
   
  Behold one of the tower piers of the church of Reims [and] one of
  those which stands between two chapels; and there is one which is a
  wall pier, and one comes from the nave of the cathedral. On all these
  piers the joints are as they should be. (21)
   
  Behold the profiles of the chapels on the preceding page, of the
  window arches and the tracery, of the diagonal ribs and the transverse
  arches and wall arches above them. (22)
   
  From the next section of the book, the chapter on carpentry and wooden
  constructions, a number of sketches are missing. Hahnloser ascribes
  this to the great demand for these drawings in the lodge. Examples of
  forms of timber roofs are limited to three. The majority of drawings
  deal with mechanical devices such as machines useful on building
  sites, in industry and for military operations, surprisingly similar
  in scope to those discussed by Vitruvius in the first century
  B.C. (23)
   
  Clearly the architect continued to be called upon to function as a
  mechanical engineer. Villard appears completely up to date with the
  mechanical experiments of his own day. His book is the first to
  demonstrate the operation of a new waterpowered sawmill involving two
  separate motions; the first on record in Europe to demonstrate a
  perpetuum mobile, of which he says that scientists long disputed how
  to make a wheel turn by itself. He seems absorbed by contemporary
  experiments with a mechanical clock system and demonstrates a
  clockwork which enables an angel on top of a church steeple to turn
  his hand at all times toward the sun and an eagle on a church lectern
  which follows the words of the deacon reading the Gospel by turning
  his head toward him. (24)
   
  Villard introduces the next section of his lodge book thus: "Here
  begins the art of drawing the principal features, as the discipline of
  geometry teaches, in order to enable one to work more easily;" and he
  says further, "On these four leaflets are figures from the discipline
  of geometry, but he who wants to know for which [kind of work] each
  figure ought to be used has to be careful to make no mistake." (25)
   
  There follow a number of small sketches of human and animal heads and
  of entire figures in various poses, by themselves or in combinations
  of two or more, with boldly superposed geometric shapes such as the
  square, the rectangle, the triangle, the pentagram and so forth that
  fit the individual contour. Villard shows how the same geometric
  figure that fits the contour of a human head also fits that of a horse
  and how different geometric figures quay be applied to the same
  head. The purpose of Villard's drawings is to teach the young mason
  how to transfer small preparatory drawings to the size and the medium
  which were called for .He also demonstrates the use of the quadratic
  net of lines, known and used since antiquity for the determination of
  the standard of proportions of the human form as well as an aid in
  transferring a small sketch to any desired scale. Villard, however,
  clearly prefers his own bold method of simple geometric
  configurations.
   
  Finally, Villard demonstrates the stonemason's first task, that of
  safe and effective building by means of mensuration. His own examples
  are few and highly selective. Master II wrote the text to them and
  added two further pages of drawings of his own with comments dealing
  with specific stonemason's problems, such as how to cut the voussoirs
  for an arch covering an oblique opening in a wall. (26)
   
  These additional demonstrations, apparently copied from some other
  manual, indicate how vital these lessons in applied geometry must have
  been to the average stonemason in contradistinction to that which the
  architect had found interesting to demonstrate.
   
  (1) Nikolaus Pevsner, "The Term 'Architect' in the Middle Ages,"
  Speculum, XVII (1942), 549-62.
   
  (2) Villard de Honnecourt: Kritische Gesamtausgabe des Bauhuttenbuches
  MS. fr. 19093 der Pariser Nationalbibliothek, ed. Hans R. Hahnloser
  (Vienna: Verlag von Anton Schroll & Co., 1953; for a more recent
  reinterpretation of some of the drawings and the text, see Frankl, The
  Gothic, pp.35-54. Hahnloser's facsimile reproductions should be used
  for the study of Villard's drawings; all references to plates give
  Hahnloser's pagination. Sec also the frontispiece taken from
  Hahnloser, plt. 20, by the permission of the publishers. Hahnloser
  also gives a complete bibliography up to 1935 and a history of the
  manuscript on pp. 5, 8, 9, 189-93, 199-200. Only 33 of the
  manuscript's original 63 or more leaves are left. Hahnloser's
  assumption that the loss occurred while the lodge book was still in
  great demand in the lodge where it was left has much to recommend
  it. We have more information about the use of lodge books and single
  drawings from later periods. They existed in an increasing number in
  the fourteenth and fifteenth centuries where large-scale building
  enterprises were under way, as at Strasbourg, Cologne, Vienna, Ulm,
  Prague, Esslingen, Milan, Florence, Cambridge and London, to name a
  few. An architect who left the service of a patron had to leave behind
  all drawings he had made in connection with that particular lodge. At
  least from the fourteenth century on, it is known that drawings
  frequently served to show the employer how the finished product was to
  look. Beginning in 1324, English documents mention "tracing houses" in
  the king's works in London; Pierre du Colombier, Les Chantiers des
  cathedrales (Paris: A. et J. Picard, 1953), pp.63-64; Hahnloser,
  Villard de Honnecourt, pp. 195-99.)
   
  (3) Unless otherwise noted, dates are taken from Hahnloser, Villard de
  Honnecourt, pp.226-32.
   
  (4) Reims cathedral was begun in 1211 and the clergy entered the choir
  in 1241; beyond these, no definite dates are available for that part
  of the building. Both Hahnloser and Frankl date Villard's visit to
  Reims as being about 1235. Villard may, however, have been at Reims
  any time after 1231, when work at the cathedral of Cambrai was
  interrupted; Hahnloser, Villard de Honnecourt, pp. 225-30.
   
  (5) Louis Grodecki, "De 1200 a 1260," in Le Vitrails francais, sous la
  haute direction du Musee des Arts Dicoratifs de Paris (Paris: Editions
  des Deux Mondes, 1958), pp.115-44.
   
  (6) Hahnloser, Villard de Honnecourt, p.76, points out that Villard
  intentionally drew both rose windows-some fifteen to twenty years
  after their completion--to appear lighter and more delicate than they
  actually were, and implies that he drew them this way to accommodate
  the increasing demand for lightness of form.
   
  (7) Hahnloser, Villard de Honnecourt, pp. 231, 236-37.
   
  (8) See Vitruvius: The Ten Books of Architecture, trans. Morris Hicky
  Morgan (Cambridge, Mass.: Harvard University Press, 1914.
   
  (9) Hahnloser, p. 4; Frankl, The Gothic, p. 48; Julius von Schlosser,
  "Materialien zur Quellenkunde der Kunstgeschichte," Sitzungsberichte
  der Kaiserlichen Akademie der Wissenschaften in Wien, 177/1,
  "Mittelalter" (Vienna: Alfred Holder 1914), 3-102, esp. p.93.
   
  (10) The English translation is Frankl's, p. 41; there and on
  following pages he changes the customary reading of the text to
  conform with his reinterpretation of the drawings on plates 35-38 and
  39-41. Passages reprinted by permission of Princeton University
  Press. Copyright, 1960. The Old French text-"(et) si troveres lc force
  de le portraiture, les trais, ensi come li ars de iometrie le
  (com)ma(n)d(e) (et) ensaigne"-is linguistically fully expounded by
  Hahnloser, pp. 11-17. 272-79.
   
  (11) Schlosser, "Materialien zur Quellenkunde," p. 93, says that
  "without doubt Villard did not intend to dissemble when quite clearly
  he did not draw from nature, for to him 'nature' meant something
  different from what it means to us; for a man of the Middle Ages it
  was impossible to consider as meaningful anything but the idea, the
  concept, behind the appearance of things. The natural form was like
  soft wax which had to yield to the artistic invention." See also
  Hahnloser, pp.268-72. The next two pages in Villard's notebook show
  several more lions in gladiatorial scenes whose prototypes go back to
  Roman or Byzantine manuscripts.
   
  (12) Hahnloser, p.263.
   
  (13) Hahnloser explains, p. 33, that the execution of this drawing is
  so sketchy and in such poor perspective that it may be assumed that
  Villard drew it from nature rather than from a sample book. It is in
  fact the first lectern of its type to be shown in a drawing, although
  soon it was to become the most commonly used type.
   
  (14) Hahnloser, pls. 54a, b, 57; Villard's use of the acanthus
  ornament to the exclusion of other floral motifs, as with his use of
  the clinging pleated drapery, is characteristic of the generation of
  sculptors of the early high gothic period. A new generation of
  sculptors of the west facades of the cathedrals of Paris and Amiens
  were already using indigenous flowers and foliage.
   
  (15) Hahnloser, pl. 17, d, e.
   
  (16) Hahnloser, pls. 18, 19. On pp. 51 and 54 Hahnloser produces
  evidence of the admiration all through Europe for the towers of Laon
  but makes the point that Villard was the first to call attention to
  the harmony of proportions of single parts and the elegance of
  transitions from one level to the next.
   
  (17) Hahnloser, pl. 20b, pp. 57-58 (and also see frontispiece);
  Hahnloser considers this "the roost personal artistic judgment of the
  high Middle Ages." On this same plate also appears the half-length
  figure of the Virgin and Child, the only representation of the Virgin
  and Child among Villard's drawings. (Reproduced by permission of Buch-
  and Kunstverlag Anton Schroll Co., Vienna).
   
  (18) Hahnloser, pl. 28c; the drawings of the elevations are
  lost. Villard appears to have made all these drawings at the lodge of
  Cambrai with the original plans before him. When building activity was
  resumed in 1239 the chapels were done in a different manner.
   
  (19) Hahnloser, pls. 60 ate, 61.
   
  (20) Hahnloser, pl. 62, 63. The English translation of this and the
  preceding three paragraphs is taken from Frankl, The Gothic,
  p.47. Also on p.47 Frankl compares Villard's comment with one added
  later by Master III, who gives a simpler, purely practical
  interpretation to the complex and aesthetically important
  architectural detail which Villard had recorded.
   
  (21) Hahnloser, pl. 63a-d.
   
  (22) Hahnloser, pl. 63e-t.
   
  (23) See Vitruvius, book X, where Vitruvius discusses and draws
  hoisting machines, water wheels, water mills, water screws, pumps,
  catapults, ballistae, and siege and defense machines.
   
  (24) Lynn White, Jr., Medieval Technology and Social Change (New York:
  Oxford University Press, 1966), pp. 118, 122, 131 (with note on
  p. 173).
   
  (25) Hahnloser, pls. 35-38; Frankl's explanation, pp. 41-46, of both
  text and drawings is simple and convincing. These drawings have
  aroused the greatest interest and have been interpreted in various
  ways, though most frequently as a rigorously formal system of fitting
  figures into a given geometric frame to standardize proportions and
  beauty, that is, a theory of proportions; Henry Focillon, Art
  d'Occident: Le Moyen Age romain et gothique (Paris: Librairie Armand
  Colin, 1938), p. 101; see also Hahnloser, pp.211-13, who speaks of
  Leitlinien, or guiding lines for proportions, which direct the hand of
  the medieval craftsman, and Schlosser, "Materialien zur Quellenkunde,"
  p.29. Colombier, p.89, clearly observes that the geometric
  configurations are imposed upon the completed figures rather than
  preceding them, and he raises doubt about the validity of the
  prevailing theories.
   
  (26) Robert Branner, "Three Problems from the Villard de Honnecourt
  Manuscript," The Art Bulletin, XXXIX/1 (1957), 61-66.
   
   ** Teresa G. Frisch, Gothic Art 1140 - c. 1450: Sources and
   Documents, University of Toronto Press in association with the
   Medieval Academy of America, 1987.


 
